name: Construcción y despliegue de Animalia en Azure App Service

env:
  AZURE_WEBAPP_NAME: animaliavet
  AZURE_WEBAPP_PACKAGE_PATH: '.'  # Usamos '.' como en el ejemplo
  DOTNET_VERSION: '8'

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Animalia/**'
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restaurar dependencias
        working-directory: Animalia
        run: dotnet restore

      - name: Construir la app
        working-directory: Animalia
        run: dotnet build --configuration Release --no-restore

      - name: Publicar la app
        working-directory: Animalia
        run: dotnet publish -c Release -o ${{ github.workspace }}/myapp  # Ruta corregida

      - name: Empaquetar la app para despliegue
        uses: actions/upload-artifact@v4
        with:
          name: animalia-package
          path: ${{ github.workspace }}/myapp  # Ruta corregida

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: none
    environment:
      name: Production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}  # URL de despliegue
    steps:
      - name: Descargar el paquete de la app
        uses: actions/download-artifact@v4
        with:
          name: animalia-package

      - name: Desplegar a Azure App Service
        id: deploy-to-webapp  # Asignamos un ID para usar la salida
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .  # Usamos '.' como en el ejemplo