name: CI/CD para ASP.NET Core en Azure

env:
  AZURE_WEBAPP_NAME: "upt-awa-app"  # Nombre de la aplicación en Azure
  DOTNET_VERSION: "8.0"             # Versión de .NET

on:
  push:
    branches: [ "main" ]
    paths:
      - "Animalia/**"
      - ".github/workflows/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restaurar dependencias
        run: dotnet restore Animalia/Animalia.sln

      - name: Compilar la aplicación
        run: dotnet build Animalia/Animalia.sln --configuration Release --no-restore

      - name: Ejecutar pruebas
        run: dotnet test Animalia/Animalia.sln --configuration Release --no-restore

      - name: Publicar la aplicación
        run: dotnet publish Animalia/Animalia.sln --configuration Release --output Animalia/bin/Release/net8.0/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Desplegar a Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: "Animalia/bin/Release/net8.0/publish"
          slot-name: production
