name: Construcción y despliegue de una aplicación MVC a Azure

env:
  AZURE_WEBAPP_NAME: upt-awa-app        # Nombre de la aplicación en Azure
  DOTNET_VERSION: '8'                   # Versión de .NET

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Animalia/**'                    # Ruta de tu aplicación
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Clonar el repositorio
      - uses: actions/checkout@v4

      # Iniciar sesión en el Docker registry (si lo usas)
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{ secrets.GHCR_TOKEN }} 

      # Construir la imagen Docker
      - name: 'Build MVC App Docker Image'
        run: |
            docker build -f Dockerfile -t ghcr.io/${{github.actor}}/shorten02:${{github.sha}} .
            docker push ghcr.io/${{github.actor}}/shorten02:${{github.sha}}

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Desplegar la aplicación a Azure Web App desde Docker
      - name: 'Desplegar a Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ghcr.io/${{github.actor}}/shorten02:${{github.sha}}
