name: CI/CD para ASP.NET Core en Azure

env:
  AZURE_WEBAPP_NAME: "upt-awa-app"        # Nombre de la aplicación en Azure
  DOTNET_VERSION: "8.0"                   # Versión de .NET
  AZURE_WEBAPP_PACKAGE_PATH: '.'  # Ruta al paquete publicado

on:
  push:
    branches: [ "main" ]
    paths:
      - "Animalia/**"
      - ".github/workflows/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restaurar dependencias
        run: cd Animalia && dotnet restore

      - name: Compilar la aplicación
        run: cd Animalia && dotnet build --configuration Release --no-restore

      - name: Publicar la aplicación
        run: cd Animalia && dotnet publish --configuration Release --output ./bin/Release/net8.0/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Descargar artefacto de la aplicación
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Desplegar a Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          restart: true
