name: CI/CD para ASP.NET Core en Azure

env:
  AZURE_WEBAPP_NAME: "upt-awa-app"  # Nombre de la aplicaci贸n en Azure
  DOTNET_VERSION: "8.0"             # Versi贸n de .NET

on:
  push:
    branches: [ "main" ]
    paths:
      - "Animalia/**"
      - ".github/workflows/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del c贸digo
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Compilar la aplicaci贸n
        run: dotnet build --configuration Release --no-restore

      - name: Ejecutar pruebas
        run: dotnet test --configuration Release --no-restore

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Desplegar a Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: "./"
